[package]
name = "lighthouse"
authors = ["abstraq <abstraq@outlook.com"]
version = "1.0.0"
license = "MIT"
edition = "2021"

[dependencies]
log = "0.4"
log4rs = "1.1.1"
tokio = { version = "1", features = ["full"] }
